application/models.py
"""Data models."""
from . import db
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash


class Result(db.Model):
    """Data model for results."""

    __tablename__ = 'scrabble_db'
    id = db.Column(
        db.Integer,
        primary_key=True
    )
    points = db.Column(
        db.String(64),
        index=False,
        unique=False,
        nullable=False
    )
    time = db.Column(
        db.String(80),
        index=False,
        unique=False,
        nullable=False
    )
    created = db.Column(
        db.DateTime,
        index=False,
        unique=False,
        nullable=False
    )

    def __repr__(self):
        return f'<Result {self.id} from {self.created}>'


class User(UserMixin, db.Model):
    """User account model."""

    __tablename__ = 'flasklogin-users'
    id = db.Column(
        db.Integer,
        primary_key=True
    )
    email = db.Column(
        db.String(40),
        unique=True,
        nullable=False
    )
    password = db.Column(
        db.String(200),
        primary_key=False,
        unique=False,
        nullable=False
    )
    created_on = db.Column(
        db.DateTime,
        index=False,
        unique=False,
        nullable=True
    )
    last_login = db.Column(
        db.DateTime,
        index=False,
        unique=False,
        nullable=True
    )

    role = db.Column(
        db.String(40),
        unique=False,
        nullable=True
    )

    def set_password(self, password):
        """Create hashed password."""
        self.password = generate_password_hash(
            password,
            method='sha256'
        )

    def check_password(self, password):
        """Check hashed password."""
        return check_password_hash(self.password, password)

    def __repr__(self):
        return '<User {}>'.format(self.email)

application/forms.py
"""Sign-up & log-in forms."""
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo, Length


class SignupForm(FlaskForm):
    """User Sign-up Form."""
    email = StringField(
        'Email',
        validators=[
            Length(min=6),
            Email(message='Enter a valid email.'),
            DataRequired()
        ]
    )
    password = PasswordField(
        'Password',
        validators=[
            DataRequired(),
            Length(min=6, message='Select a stronger password.')
        ]
    )
    confirm = PasswordField(
        'Confirm Your Password',
        validators=[
            DataRequired(),
            EqualTo('password', message='Passwords must match.')
        ]
    )
    submit = SubmitField('Register')


class LoginForm(FlaskForm):
    """User Log-in Form."""
    email = StringField(
        'Email',
        validators=[
            DataRequired(),
            Email(message='Enter a valid email.')
        ]
    )
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Log In')


class ResultForm(FlaskForm):
    """Result Form."""
    points = IntegerField(
        'Points',
        validators=[
            DataRequired(message="What was the SUM of scores in the game?\
                [Integer]"),
        ]
    )
    time = IntegerField(
        'Time',
        validators=[
            DataRequired(message="How many minutes did the game last?\
                [Integer]"),
        ]
    )
    submit = SubmitField('Submit')

application/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

db = SQLAlchemy()
login_manager = LoginManager()


def create_app():
    """Initialize the core application."""
    app = Flask(__name__, instance_relative_config=False)
    app.config.from_object('config.Config')

    # Initialize Plugins
    db.init_app(app)
    login_manager.init_app(app)

    with app.app_context():
        from . import routes
        from . import auth

        # Register Blueprints
        app.register_blueprint(routes.main_bp)
        app.register_blueprint(auth.auth_bp)

        db.create_all()

        return app

application/auth.py
"""Routes for user authentication."""
from flask import (
    Blueprint, redirect, render_template, flash, request, session, url_for
)
from flask_login import login_required, logout_user, current_user, login_user
from functools import wraps
from .forms import LoginForm, SignupForm
from .models import db, User, Result
from . import login_manager


# Blueprint Configuration
auth_bp = Blueprint(
    'auth_bp', __name__,
    template_folder='templates',
    static_folder='static'
)


def admin_required(f):
    @wraps(f)
    def wrap(*args, **kwargs):
        if current_user.is_authenticated:
            if current_user.role == "Admin":
                return f(*args, **kwargs)
        else:
            flash("You need to be an admin to view this page.")
            return redirect(url_for('main_bp.index'))

    return wrap


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    """
    Log-in page for registered users.

    GET requests serve Log-in page.
    POST requests validate and redirect user to dashboard.
    """
    # Bypass if user is logged in
    if current_user.is_authenticated:
        return redirect(url_for('main_bp.index'))

    form = LoginForm()
    # Validate login attempt
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.check_password(password=form.password.data):
            login_user(user)
            next_page = request.args.get('next')
            return redirect(next_page or url_for('main_bp.index'))
        flash('Invalid username/password combination')
        return redirect(url_for('auth_bp.login'))
    return render_template(
        'login.html',
        form=form,
        title='Log in.',
        results=Result.query.all(),
        template='login-page',
        body="Log in with your User account."
    )


@auth_bp.route('/signup', methods=['GET', 'POST'])
@admin_required
def signup():
    """
    User sign-up page.

    GET requests serve sign-up page.
    POST requests validate form & user creation.
    """
    form = SignupForm()
    if form.validate_on_submit():
        existing_user = User.query.filter_by(email=form.email.data).first()
        if existing_user is None:
            user = User(
                email=form.email.data,
            )
            user.set_password(form.password.data)
            db.session.add(user)
            db.session.commit()  # Create new user
            return redirect(url_for('main_bp.index'))
        flash('A user already exists with that email address.')
    return render_template(
        'signup.html',
        title='Create an Account.',
        results=Result.query.all(),
        form=form,
        template='signup-page',
        body="Sign up for a user account."
    )


@login_manager.user_loader
def load_user(user_id):
    """Check if user is logged-in on every page load."""
    if user_id is not None:
        return User.query.get(user_id)
    return None


@login_manager.unauthorized_handler
def unauthorized():
    """Redirect unauthorized users to Login page."""
    flash('You must be logged in to view that page.')
    return redirect(url_for('auth_bp.login'))


@auth_bp.route("/logout")
@login_required
def logout():
    """User log-out logic."""
    logout_user()
    return redirect(url_for('auth_bp.login'))

application/routes.py
from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
)
from flask_login import current_user, login_required
from datetime import datetime
from .forms import ResultForm
from .models import db, Result

# Blueprint Configuration
main_bp = Blueprint(
    'main_bp', __name__,
    template_folder='templates',
    static_folder='static'
)


@main_bp.route('/', methods=['GET', 'POST'])
@login_required
def index():
    form = ResultForm()
    if form.validate_on_submit():
        points = form.points.data
        time = form.time.data
        if points and time:
            new_result = Result(
                points=points,
                time=time,
                created=datetime.now()
            )
            db.session.add(new_result)
            db.session.commit()
            return redirect(url_for('main_bp.index'))
    return render_template(
        'results.html',
        form=form,
        results=Result.query.all(),
        current_user=current_user,
    )

application/templates/index.html
<html>
  <head>
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <script src="https://d3js.org/d3.v6.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-10">
          <h1>Scrabble</h1>
        </div>
        <div class="col-md-2 user-info">
          {% if current_user.is_authenticated %}
            <p>Hi {{ current_user.email }}!</p>
            <a href="{{ url_for('auth_bp.logout') }}">Log out</a>
          {% endif %}
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 chart-wrapper">
          <canvas id="myChart" width="400" height="400"></canvas>
        </div>
        <div class="col-md-6 content-wrapper">
        {% block content %}{% endblock %}
        </div>
      </div>
    </div>
    <hr>
    {% block result_content %}{% endblock %}
    
    <script>
      var dataset = [
        {% for item in results %}
          {
            x: {{item.time}},
            y: {{item.points}},
          },
        {% endfor %}
      ]

      new Chart(document.getElementById("myChart"), {
        type: 'scatter',
        data: {
          datasets: [{
            data: dataset,
            pointRadius: 5,
            pointHoverRadius: 6,
            fill: false,
          }]
        },
        options: {
          lineheight: 1,
          legend: {
            display: false,
          },
          scales: {
            yAxes: [{
              ticks: {
                suggestedMin: 0,
              }
            }]
          },
          title: {
            display: false,
          },
          hover: {
           mode: 'index',
           intersect: true
          },
        }
      });
    </script>
  </body>
</html>

application/templates/login.html
{% extends "index.html" %}

{% block content %}
  <div class="form-wrapper">

    {% for message in get_flashed_messages() %}
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
      </div>
    {% endfor %}

    <h1>Log In</h1>

    <form method="POST" action="/login">
      {{ form.csrf_token }}

      <fieldset class="email">
        {{ form.email.label }}
        {{ form.email(placeholder='youremail@example.com') }}
        {% if form.email.errors %}
          <ul class="errors">
            {% for error in form.email.errors %}
              <li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <fieldset class="password">
        {{ form.password.label }}
        {{ form.password }}
        {% if form.email.errors %}
          <ul class="errors">
            {% for error in form.password.errors %}
              <li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <div class="submit-button">
        {{ form.submit }}
      </div>

    </form>
  </div>
{% endblock %}

application/templates/results.html
{% extends "index.html" %}


{% block content %}
<div class="form-wrapper">

  {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      {{ message }}
    </div>
  {% endfor %}

  <h1>Sign Up</h1>

  <form method="POST" action="/">
    {{ form.csrf_token }}

    <fieldset class="points">
      {{ form.points.label }}
      {{ form.points(placeholder='500') }}
      {% if form.points.errors %}
        <ul class="errors">
          {% for error in form.points.errors %}
            <li>{{ error }}</li>{% endfor %}
        </ul>
      {% endif %}
    </fieldset>

    <fieldset class="time">
      {{ form.time.label }}
      {{ form.time(placeholder='75') }}
      {% if form.time.errors %}
        <ul class="errors">
          {% for error in form.time.errors %}
            <li>{{ error }}</li>{% endfor %}
        </ul>
      {% endif %}
    </fieldset>

    <div class="submit-button">
      {{ form.submit }}
    </div>

  </form>
</div>
{% endblock %}

{% block result_content %}
    <div class="container">
      {% for result in results %}
        <ul id="result.resultname">
          <li>
              <span class="field-name">Points:</span>
              <span class="field-value">{{ result.points }}</span>
          </li>
          <li>
              <span class="field-name">Time:</span>
              <span class="field-value">{{ result.time }} minutes</span>
          </li>
          <li>
              <span class="field-name">Created:</span>
              <span class="field-value">{{ result.created }}</span>
          </li>
        </ul>
      {% endfor %}
    </div>
{% endblock %}

application/templates/signup.html
{% extends "index.html" %}

{% block content %}
  <div class="form-wrapper">

    {% for message in get_flashed_messages() %}
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
      </div>
    {% endfor %}

    <h1>Sign Up</h1>

    <form method="POST" action="/signup">
      {{ form.csrf_token }}

      <fieldset class="email">
        {{ form.email.label }}
        {{ form.email(placeholder='youremail@example.com') }}
        {% if form.email.errors %}
          <ul class="errors">
            {% for error in form.email.errors %}
              <li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <fieldset class="password">
        {{ form.password.label }}
        {{ form.password }}
        {% if form.password.errors %}
          <ul class="errors">
            {% for error in form.password.errors %}
              <li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <fieldset class="confirm">
        {{ form.confirm.label }}
        {{ form.confirm }}
        {% if form.confirm.errors %}
          <ul class="errors">
            {% for error in form.confirm.errors %}
              <li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <div class="submit-button">
        {{ form.submit }}
      </div>

    </form>

    <div class="login-signup">
      <span>Already have an account? <a href="{{ url_for('auth_bp.login') }}">Log in.</a></span>
    </div>
  </div>
{% endblock %}